<div class="table-responsive">
                                <table id="mainTable" class="table table-striped m-b-0">
                                    <thead>
                                        <tr>
                                            <th>نام</th>
                                            <th>هزینه</th>
                                            <th>سود</th>
                                            <th>تفریح</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>ماشین</td>
                                            <td>100</td>
                                            <td>200</td>
                                            <td>0</td>
                                        </tr>
                                        <tr>
                                            <td>دوچرخه</td>
                                            <td>330</td>
                                            <td>240</td>
                                            <td>1</td>
                                        </tr>
                                        <tr>
                                            <td>بیلیارد</td>
                                            <td>430</td>
                                            <td>540</td>
                                            <td>3</td>
                                        </tr>
                                        <tr>
                                            <td>قایق بادبانی</td>
                                            <td>100</td>
                                            <td>200</td>
                                            <td>0</td>
                                        </tr>
                                        <tr>
                                            <td>اسکی</td>
                                            <td>330</td>
                                            <td>240</td>
                                            <td>1</td>
                                        </tr>
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th><strong>مجموع</strong></th>
                                            <th></th>
                                            <th></th>
                                            <th></th>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
